.PHONY: all clean algorithm gamemanager simulator

all: algorithm gamemanager simulator

algorithm:
	$(MAKE) -C Algorithm

gamemanager:
	$(MAKE) -C GameManager

simulator:
	$(MAKE) -C Simulator

clean:
	$(MAKE) -C Algorithm clean
	$(MAKE) -C GameManager clean
	$(MAKE) -C Simulator clean